POST {{base_url_prod}}/openai
Content-Type: application/json

{
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Who won the world series in 2020?"
    },
    {
      "role": "assistant",
      "content": "The Los Angeles Dodgers won the World Series in 2020."
    },
    {
      "role": "user",
      "content": "Where was it played?"
    }
  ]
}

###

POST {{base_url_prod}}/speech
Content-Type: application/json

{
  "content": "You are a therapist giving a therapy session. Give me a 435 word inspirational meditation session about overcoming opioid addiction and chronic pain. Only output the actual session without ambiance instructions, quotation marks or Certainly, here's a 435-word inspirational meditation session on overcoming opioid addiction:. Remember the key points for future reference"
}